### ISSUE TITLE
No handset_detection.specs.general_aliases values for iPhone, iPad etc.

### ISSUE THREAD

**Issue by OzWookiee** [HandsetDetection/logstash-filter-handsetdetection#13]
When using the field handset_detection.specs.general_aliases for a visualisation it gives skewed data compared to handset_detection.specs.general_model as shown here: http://imgur.com/a/fW1YX

As there are no Alias for Windows PC, iPhone, OS X PC or iPad then it seems like we don't get any traffic from those devices. Looking at the general_model though, it's hard to make out which Samsung devices are being used as the model number is not commonly used (hence the reason for the alias).

Perhaps if there is no general_alias then it can default to general_model?

**Comment by elricho** [comment]
Hey @OzWookie, Thanks for the suggestion. We're going to extend the schema to include a general_device_name field which will evaluate as you suggest ie. the first alias if available otherwise general_vendor + ' ' + general_model. We're also going to add general_platform_name, general_browser_name and general_app_name too .. I'll report back next week then this update is out.

**Comment by elricho** [comment]
Merged

**Comment by elricho** [comment]
Doh - closed wrong issue.

**Comment by OzWookiee** [comment]
Awesome. Thanks.

**Comment by elricho** [comment]
@OzWookie : I've just merged this update. New convenience field names are general_device_name, general_platform_name, general_browser_name and general_app_name.

**Comment by elricho** [comment]
@OzWookiee : Version 4.1.7 has the updates. 👍

**Comment by OzWookiee** [comment]
Awesome I'll update and let you know.

**Comment by OzWookiee** [comment]
WIN
http://imgur.com/i7bwNq6

**Comment by elricho** [comment]
👍  :-)
